// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckPythonEnvironment() {
  return window['go']['main']['App']['CheckPythonEnvironment']();
}

export function GenerateImage(arg1, arg2) {
  return window['go']['main']['App']['GenerateImage'](arg1, arg2);
}

export function GetImageData(arg1) {
  return window['go']['main']['App']['GetImageData'](arg1);
}

export function GetInstallLog() {
  return window['go']['main']['App']['GetInstallLog']();
}

export function SaveImageToDesktop(arg1) {
  return window['go']['main']['App']['SaveImageToDesktop'](arg1);
}
