// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckPythonEnvironment():Promise<main.CheckPythonStatus>;

export function GenerateImage(arg1:string):Promise<main.GenerateImageResult>;

export function GetImageData(arg1:string):Promise<string>;

export function GetInstallLog():Promise<main.LogMessage>;

export function SaveImageToDesktop(arg1:string):Promise<string>;
